# Generated by Django 4.1.3 on 2022-11-08 09:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityNo', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('DoB', models.DateTimeField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('mobileNoIndian', models.CharField(max_length=10)),
                ('alternativeNo', models.CharField(max_length=15)),
                ('personalMail', models.CharField(max_length=200)),
                ('collegeMail', models.CharField(max_length=200)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=30)),
                ('motherNo', models.CharField(max_length=15)),
                ('fatherNo', models.CharField(max_length=15)),
                ('fullAddress', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('nationality', models.CharField(max_length=15)),
                ('planAfterGraduate', models.CharField(max_length=15)),
                ('sslcPer', models.FloatField(max_length=5)),
                ('sslcYoP', models.CharField(max_length=4)),
                ('sslcBoard', models.CharField(max_length=35)),
                ('hsePer', models.CharField(max_length=5)),
                ('hseYoP', models.CharField(max_length=4)),
                ('hseBoard', models.CharField(max_length=30)),
                ('nameOfUG', models.CharField(max_length=10)),
                ('ugPer', models.CharField(max_length=5)),
                ('ugCgpa', models.CharField(max_length=5)),
                ('ugYoP', models.CharField(max_length=4)),
                ('collegeNameUg', models.CharField(max_length=50)),
                ('ugUniversity', models.CharField(max_length=50)),
                ('entranceRank', models.CharField(max_length=6)),
                ('mcaAggregateCgpa', models.CharField(max_length=4)),
                ('activeArrears', models.CharField(max_length=2)),
                ('historyOfArrears', models.CharField(max_length=2)),
                ('examsNotAttended', models.CharField(max_length=2)),
                ('pgUniversity', models.CharField(max_length=50)),
                ('technicalSkills', models.CharField(max_length=500)),
                ('certifications', models.CharField(max_length=500)),
                ('internships', models.CharField(max_length=500)),
                ('workExperience', models.CharField(max_length=500)),
                ('projectGithub', models.CharField(max_length=500)),
                ('linkedIn', models.CharField(max_length=500)),
                ('achievement', models.CharField(max_length=500)),
                ('languagesKnown', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpoName', models.CharField(max_length=50)),
                ('tpoMail', models.EmailField(max_length=75)),
                ('tpoPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_tpo', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
