# Generated by Django 3.2.12 on 2022-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreg',
            name='admno',
        ),
        migrations.AddField(
            model_name='studentreg',
            name='admino',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
