# Generated by Django 3.2.12 on 2022-11-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20221113_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
