# Generated by Django 3.2.12 on 2022-11-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_remove_mcastudentdetails_admino'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentdetails',
            name='admino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg'),
        ),
    ]
