# Generated by Django 3.2.12 on 2022-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_mcastudentdetails_admino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('salary_package', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('last_date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='btechstudentdetails',
            name='DoB',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='DoB',
            field=models.DateField(max_length=10),
        ),
    ]
