# Generated by Django 3.2.12 on 2022-11-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_studentreg_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='admino',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(default='youremail@gmail.com', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
