# Generated by Django 3.2.12 on 2022-11-22 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_auto_20221122_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyDrive',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applied_on', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='drives',
            old_name='id',
            new_name='drive_id',
        ),
        migrations.CreateModel(
            name='Placed',
            fields=[
                ('placed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('drive_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.applydrive')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg')),
            ],
        ),
        migrations.AddField(
            model_name='applydrive',
            name='drive_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.drives'),
        ),
        migrations.AddField(
            model_name='applydrive',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg'),
        ),
    ]
