# Generated by Django 3.2.12 on 2022-11-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_auto_20221122_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechstudentdetails',
            name='admino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg'),
        ),
    ]
