# Generated by Django 3.2.12 on 2022-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_btechstudentdetails_admino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btechstudentdetails',
            name='linkedIn',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='btechstudentdetails',
            name='projectGithub',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='linkedIn',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='projectGithub',
            field=models.URLField(max_length=500),
        ),
    ]
