# Generated by Django 3.2.12 on 2022-11-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_auto_20221122_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
