# Generated by Django 3.2.12 on 2022-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_auto_20221118_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btechstudentdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='btechstudentdetails',
            name='title',
        ),
        migrations.RemoveField(
            model_name='btechstudentdetails',
            name='universityNo',
        ),
        migrations.RemoveField(
            model_name='mcastudentdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mcastudentdetails',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mcastudentdetails',
            name='universityNo',
        ),
        migrations.AddField(
            model_name='studentreg',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreg',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
