# Generated by Django 3.2.12 on 2022-11-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_auto_20221118_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentdetails',
            name='first_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg'),
        ),
    ]
