# Generated by Django 3.2.12 on 2022-11-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_mcastudentdetails_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcastudentdetails',
            name='first_name',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='campus.studentreg'),
            preserve_default=False,
        ),
    ]
